name: Xcode - Build and Analyze

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:

      - uses: maxim-lobanov/setup-xcode@v1
        with: 
          xcode-version: latest
        
      - name: check Xcode version
        run: /usr/bin/xcodebuild -version
    
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: iOS build
        run: 
          xcodebuild -sdk iphonesimulator -configuration Debug -workspace "SwiftUI_Catelog.xcworkspace" -scheme "SwiftUI_Catelog" -derivedDataPath $(pwd)
