name: Xcode - Build and Analyze

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    env:
      project: 'SwiftUICatelog.xcodeproj'
      scheme: 'SwiftUICatelog'
      sdk: 'iphonesimulator'
      destination: 'platform=iphonesimulator, OS=latest, name=iPhone16Pro'

    steps:

      - uses: maxim-lobanov/setup-xcode@v1
        with: 
          xcode-version: latest
        
      - name: check Xcode version
        run: /usr/bin/xcodebuild -version
    
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: build 
        run: xcodebuild -project '${{ env.project }}' -scheme ${{ env.scheme }} -sdk ${{ env.sdk }} -destination ${{ env.destination }}
          # xcodebuild -sdk iphonesimulator -configuration Debug -workspace "SwiftUI_Catelog.xcodeproj" -scheme "SwiftUI_Catelog" -derivedDataPath $(pwd)
