name: Xcode - Build and Analyze

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest
    strategy:  
      matrix:
       run-config:
         - { project: 'SwiftUICatelog.xcodepro', scheme: 'SwiftUICatelog', sdk: 'iphonesimulator', destination: 'platform=iOS Simulator,OS=latest,name=iPhone 16 Pro' }

    env:
      project: 'SwiftUICatelog.xcodeproj'
      scheme: 'SwiftUICatelog'
      sdk: 'iphonesimulator'
      destination: 'platform=iOS Simulator, OS=latest, name=iPhone 16 Pro'

    steps:

      - uses: maxim-lobanov/setup-xcode@v1
        with: 
          xcode-version: latest
        
      - name: check Xcode version
        run: /usr/bin/xcodebuild -version
    
      - name: Checkout
        uses: actions/checkout@v4

      # - name: List sims
        # run: xcrun simctl list devices
        
      - name: build 
        run: xcodebuild build -project '${{ env.project }}' -scheme ${{ env.scheme }} -sdk ${{ env.sdk }} -destination ${{ env.destination }}
          # xcodebuild -sdk iphonesimulator -configuration Debug -workspace "SwiftUI_Catelog.xcodeproj" -scheme "SwiftUI_Catelog" -derivedDataPath $(pwd)
